---
- name: Aprovisionamiento Corporativo
  hosts: routers
  gather_facts: no

  vars_files:
    - ../vars/vars_005D-07.yaml

  tasks:

    - name: Configurar hostname
      ios_config:
        lines:
          - hostname {{ router.hostname }}

    - name: Configurar Loopback10
      ios_config:
        lines:
          - ip address {{ router.loopback_ip }} {{ router.loopback_mask }}
        parents: interface Loopback10

    - name: Configurar descripcion WAN
      ios_config:
        lines:
          - description {{ router.descripcion_wan }}
        parents: interface GigabitEthernet1

    - name: Configurar banner
      ios_config:
        lines:
          - banner motd ^{{ router.banner }}^

    - name: Configurar servidor NTP
      ios_config:
        lines:
          - ntp server {{ router.ntp_server }}

    - name: Habilitar NETCONF
      ios_config:
        lines:
          - netconf-yang

    - name: Habilitar HTTPS
      ios_config:
        lines:
          - ip http secure-server

    - name: Habilitar RESTCONF
      ios_config:
        lines:
          - restconf
